# .pre-commit-config.yaml

exclude: 'docs|node_modules|migrations|terraform|.git|.tox'
default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [pre-commit]
        language: system
        entry: bash -c 'PYTHONPATH="$PYTHONPATH:$PWD" mypy'
        types: [python]
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        stages: [ pre-commit ]
        language: system
        entry: ruff format
        types: [ python ]
        pass_filenames: false
      - id: ruff-check
        name: ruff-check
        stages: [ pre-commit ]
        language: system
        entry: ruff check packages --fix
        types: [ python ]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-ast
      - id: check-symlinks
      - id: forbid-new-submodules
