"""

Revision ID: ef0279dd14c3
Revises: 7421e85348dc
Create Date: 2026-06-07 17:08:23.938774+00:00

"""

from typing import Any, Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

JOB_STATUS_VALUES = ("PUBLISHED", "CLAIMED", "IN_PROGRESS", "COMPLETED", "FAILED", "CANCELLED")

# revision identifiers, used by Alembic.
revision: str = "ef0279dd14c3"
down_revision: Union[str, Sequence[str], None] = "7421e85348dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _id_type() -> Any:
    return sa.BigInteger().with_variant(sa.Integer(), "sqlite")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == "postgresql"
    id_type = _id_type()

    job_status_enum = sa.Enum(*JOB_STATUS_VALUES, name="job_status", native_enum=False)
    pg_job_status_enum = postgresql.ENUM(*JOB_STATUS_VALUES, name="job_status", create_type=False)
    job_status_type = pg_job_status_enum if is_postgresql else job_status_enum
    json_type = sa.JSON().with_variant(sa.dialects.postgresql.JSONB(astext_type=sa.Text()), "postgresql")

    if is_postgresql:
        postgresql.ENUM(*JOB_STATUS_VALUES, name="job_status").create(bind, checkfirst=True)

    handoff_job_constraints: list[sa.CheckConstraint] = []
    if is_postgresql:
        handoff_job_constraints = [
            sa.CheckConstraint("jsonb_typeof(constraints) = 'array'", name="chk_constraints_is_array"),
            sa.CheckConstraint("jsonb_typeof(context_payload) = 'object'", name="chk_payload_is_object"),
        ]

    op.create_table(
        "handoff_job",
        sa.Column("id", id_type, autoincrement=True, nullable=False),
        sa.Column("parent_job_id", id_type, nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("context_payload", json_type, nullable=False),
        sa.Column("status", job_status_type, nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("source_agent_id", id_type, nullable=False),
        sa.Column("target_role_id", id_type, nullable=False),
        sa.Column("assignee_agent_id", id_type, nullable=True),
        sa.Column("constraints", json_type, nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_agent_id"],
            ["agent_identity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_job_id"],
            ["handoff_job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_id"],
            ["agent_identity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_role_id"],
            ["target_role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        *handoff_job_constraints,
    )
    op.create_index(
        "idx_handoff_job_assignee_status",
        "handoff_job",
        ["assignee_agent_id", "status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_handoff_job_source_status",
        "handoff_job",
        ["source_agent_id", "status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_handoff_job_status_created", "handoff_job", ["status", sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index(
        "idx_handoff_job_target_role_status",
        "handoff_job",
        ["target_role_id", "status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "job_artifact",
        sa.Column("id", id_type, autoincrement=True, nullable=False),
        sa.Column("job_id", id_type, nullable=False),
        sa.Column("artifact_type", sa.Text(), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=False),
        sa.Column("artifact_checksum", sa.Text(), nullable=True),
        sa.Column("metadata_json", json_type, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["handoff_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_job_artifact_job", "job_artifact", ["job_id"], unique=False)
    op.create_table(
        "job_event",
        sa.Column("id", id_type, autoincrement=True, nullable=False),
        sa.Column("job_id", id_type, nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("previous_status", job_status_type, nullable=True),
        sa.Column("current_status", job_status_type, nullable=False),
        sa.Column("actor_agent_id", id_type, nullable=True),
        sa.Column("payload_json", json_type, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_agent_id"],
            ["agent_identity.id"],
        ),
        sa.ForeignKeyConstraint(["job_id"], ["handoff_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_job_event_job_created", "job_event", ["job_id", sa.literal_column("created_at ASC")], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == "postgresql"

    op.drop_index("idx_job_event_job_created", table_name="job_event")
    op.drop_table("job_event")
    op.drop_index("idx_job_artifact_job", table_name="job_artifact")
    op.drop_table("job_artifact")
    op.drop_index("idx_handoff_job_target_role_status", table_name="handoff_job")
    op.drop_index("idx_handoff_job_status_created", table_name="handoff_job")
    op.drop_index("idx_handoff_job_source_status", table_name="handoff_job")
    op.drop_index("idx_handoff_job_assignee_status", table_name="handoff_job")
    op.drop_table("handoff_job")

    if is_postgresql:
        sa.Enum(*JOB_STATUS_VALUES, name="job_status").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
